---
 - hosts: planet-express

   tasks:
    - name: "figlet - uninstall figlet"
      apt:
        name: figlet
        state: absent
      become: True

    - name: "bastet - uninstall bastet"
      apt:
        name: bastet
        state: absent
      become: True

    - name: "ninvaders - uninstall ninvaders"
      apt:
        name: ninvaders
        state: absent
      become: True

    
